### ISSUE TITLE
2D projection + bilinear interpolation 추가

### ISSUE THREAD

**Issue by ddeokho** [nnstreamer-mobile/nnstreamer#19]
이전에 2D spherical projection 후 해상도를 키워 sparse한 것을 없애는 방향으로 하겠다고 했는데 

- [이전 내용](https://github.com/nnstreamer-preprocessor/nnstreamer/issues/7) 

적정한 프레임의 크기를 찾아 크기를 키우다보니 프레임 내에 빈 곳이 많이 생겼다. 그래서 높이기 위해 bilinear interpolation 과정을 추가로 거치도록 했다.

![image](https://user-images.githubusercontent.com/20199818/78421040-b0648500-768f-11ea-8f93-fd7203dd5c82.png)

- [bilinear interpolation 코드](https://github.com/nnstreamer-preprocessor/nnstreamer-gstreamer/blob/d148123d27b9c7e90bb9f3e7837146562aaa69f3/nnstreamer_example_object_detection_tf4.cc#L568)

- 추가했을 때 
![Screenshot from 2020-04-03 19-27-32](https://user-images.githubusercontent.com/20199818/78421092-17823980-7690-11ea-8a42-1afc76c81d7e.png)

- 추가하지 않았을 때
![Screenshot from 2020-04-03 19-46-36](https://user-images.githubusercontent.com/20199818/78421095-1bae5700-7690-11ea-8a1f-bb0d0e860738.png)

- 이미지
![0000000038](https://user-images.githubusercontent.com/20199818/78422887-9893fd80-769d-11ea-8323-fe96254da032.png)

fps 차이가 거의 없었기 때문에 bilinear interpolation을 추가해 시험해도 괜찮다고 생각. 하지만 이렇게 해도 ssdlite_mobilenet_v2.pb가 인지하지 못한다.
 1) 맞는 모델로 교체한다.
   - 교체할 때 나오는 에러를 해결해야 하며, 어떤 모델로 해야할 지 정해야 한다.(다시 아직 해결되지 않은 모델 문제로 회기)
https://github.com/nnstreamer-preprocessor/nnstreamer/issues/17
  
2) 특정 피처(차?)만 남기도 주위를 다 제거한 후에도 잡히지 않는지 궁금.

**Comment by ddeokho** [comment]
차만 남기고 돌려봤는데 안잡히네요..


우선 ground라고 표현하는 게 맞는 지 모르겠는데 바닥에 원형 제거하고
- 제거 전 
![Screenshot from 2020-04-04 18-03-29](https://user-images.githubusercontent.com/20199818/78424521-317c4600-76a9-11ea-8c96-3b05c53e1526.png)

- 제거 후
![Screenshot from 2020-04-04 19-19-11](https://user-images.githubusercontent.com/20199818/78424523-32ad7300-76a9-11ea-9cf5-73a6f75f44d1.png)

필터를 range 뿐 아니라 intensity도 추가해 구성했네요.

![Screenshot from 2020-04-04 19-17-30](https://user-images.githubusercontent.com/20199818/78424576-8d46cf00-76a9-11ea-98fa-c82895b81d71.png)

그렇게 위와 같은 형태의 차만 뽑은 후 돌렸는데 역시 안잡히는 거면 맞는 모델을 구성하고 교체하는 게 맞을 거 같아요.

![Screenshot from 2020-04-04 19-25-45](https://user-images.githubusercontent.com/20199818/78424689-31c91100-76aa-11ea-95a8-9a293766fd01.png)


그리고 자전거 탄 사람은 너무 얇긴한데 확실히 ground를 제거하니 깔끔하네요.

**Comment by hayleyshim** [comment]
덕호님, 감사합니다. 
논문 작성시, bilinear interpolation 부분 추가할게요. 
기존의 dataset과 달리 모델이 인지하지 못하는 문제가 현재 data가 너무 sparse한 것인데
Sqeezenet 모델로 교체하면 해결되면 다행이지만 현재 모델 교체 시 이슈가 있어 걱정이네요.

이전 dataset에 velodyne point data를 적용했을 때 
dataset 양이 적었지만 sparse 하지 않았기 때문에 같은 mobile_v2 모델에서도 인식이 되었다면

현재 모델 교체보다도 다른 dataset을 적용하는게 더 빠르지 않을까싶기도 해요.

**Comment by ddeokho** [comment]
넵 다른 데이터셋은 구하지 않아도 될 것 같고 아래 적으신 내용의 제 생각은 여기에 적어 놓았어요!

https://github.com/nnstreamer-preprocessor/nnstreamer/issues/17#issuecomment-609020050
