### ISSUE TITLE
nnstreamer 사용하는 이유에 대한 궁금증이 생겼습니다

### ISSUE THREAD

**Issue by yesolyun** [nnstreamer-mobile/nnstreamer#9]
아까 저녁에 회의 때 밤동안 tensorflow로 저장한 모델을(.pb파일) cpp에서 불러오도록 하는 코드를 짜보겠다고 말씀드렸었는데... 이 부분을 작업하다보니 모바일 환경에서 직접 올려볼것이 아니라 어차피 ubuntu에서 작업할거면 저희가 자체적으로 cc파일을 작성하는 것과 nnstreamer를 이용하여 build하는 것에 있어 차이가 크게 있는가 궁금해서 이슈를 올려봅니다.

https://dev-strender.github.io/articles/2017-10/tensorflow-load-model-with-cpp 와 같은 예제들을 이용해서 코드를 짜고 있는데 nnstreamer에 대한 파악이 오늘까지 끝난다면 그대로 가는것도 좋은 방향이라 생각하지만 만약 큰 차이가 없다면 nnstreamer를 버리고 딥러닝 쪽에 더 집중하는 방식으로 진행하는 건 어떨까 합니다.

+)gstreamer 사용때문에 nnstreamer가 필요한걸까요?

**Comment by DownyBehind** [comment]
근본적인 물음인데 ㅎㅎ 사실 모바일 환경에서 테스트해보려고 nnstreamer를 선택한거에요. on-device 환경에서 3d object detection model을 돌려보려고요...ㅎㅎ 

근데 현재 사실 많이 방향이 변경되긴 했죠 ㅎㅎ

**Comment by yesolyun** [comment]
> 근본적인 물음인데 ㅎㅎ 사실 모바일 환경에서 테스트해보려고 nnstreamer를 선택한거에요. on-device 환경에서 3d object detection model을 돌려보려고요...ㅎㅎ
> 
> 근데 현재 사실 많이 방향이 변경되긴 했죠 ㅎㅎ

아 그렇군요ㅎㅎ 감사합니다!!

**Comment by hayleyshim** [comment]
네, 처음엔 nnstreamer 오픈소스를 활용해서 on device 환경에서 딥러닝을 구현해보는게 목표였죠. 남은 시간 현재 이슈에 집중하고 이따 모임때 얘기해봐요

nnstreamer를 사용하려고보니 gstreamer에 대한 이해가 필요해서 파악했던거죠

**Comment by jwkanggist** [comment]
목표가 수정되어서 더이상 사용할 필요가 없는데 
프로젝트가 진행의 장애가 되고 있다고 한다면 조금 고려를 해봐야겠네요
